version: '3.9'

services:
  mysql:
    build: ./database
    image: custom-mysql:1.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: loginapp
    volumes:
      - db_data:/var/lib/mysql
    deploy:
      replicas: 1
    networks:
      - webapp

  app:
    build: ./webapp
    image: custom-nginx:1.0
    ports:
      - "8081:80"
    deploy:
      replicas: 3
    networks:
      - webapp

volumes:
  db_data:

networks:
  webapp:
    driver: overlay

